sudo: required
services:
  - docker

before_install:
  - docker build -t royastro-upstream/docker-react -f Dockerfile.dev .

script:
  - docker run royastro-upstream/docker-react npm run test

deploy:
  provider: elasticbenastalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-552816458238"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"