sudo: required
services:
  - docker

before_install:
  - docker build -t royastro-upstream/docker-react -f Dockerfile.dev .

script:
  - docker run royastro-upstream/docker-react #*** commented as tests won't dettach **** npm run test -- --coverage --forceExit --detectOpenHandles --maxWorkers=10
  

